%example of cleaning script
% better not change it, for editing save it with another name in Documents/MATLAB
fileName = 'c,rfhp0.1Hz';
p=pdf4D(fileName);
cleanCoefs = createCleanFile(p, fileName,...
    'byLF',256 ,'Method','Adaptive',...
    'xClean',[4,5,6],...
    'chans2ignore',[74,204],...
    'byFFT',0,...
    'HeartBeat',0,... % for automatic HB cleaning change 0 to []
    'maskTrigBits', 512);
