%example of cleaning script
% better not change it, for editing save it with another name in Documents/MATLAB
fileName = 'c,rfhp1.0Hz';
p=pdf4D(fileName);
cleanCoefs = createCleanFileG(p, fileName,...
    'byLF',256 ,'Method','Adaptive',...
    'xClean',[4,5,6],...
    'chans2ignore',[74,204],...
    'byFFT',0,...
    'HeartBeat',0,...
    'maskTrigBits', 512);