function dsel(obj)

%Dsel Data Selector
%obj - pdf4D object

%%%%%     Setup Dsel Figure     %%%%

%figure
figure_name = 'Data Selector';
h.fig = figure( ...
    'MenuBar', 'none', ...
    'Tag', 'init', ... %to init lists
    'NumberTitle', 'off', ...
    'Name', figure_name, ...
    'Position', [100 100 1200 400]);
setappdata(h.fig, 'Name', figure_name);

if ispc
    save_path = pwd;
    config_name = '';
    tool_list = {'Save List'};
else
    config_name = '~/.pdf4D/dsel.cnf';

    if exist('~/.pdf4D', 'dir') == 7
        if exist(config_name, 'file') == 2
            load(config_name, '-mat');
        end
    else
        mkdir('~/', '.pdf4D');
    end

    if exist('config', 'var') ~= 1
        config = struct( ...
            'data_path', {{}}, ...
            'tool_list', {{'< Save List >'}}, ...
            'save_path', pwd);
        save(config_name, 'config', '-mat');
    end
    tool_list = config.tool_list;
    save_path = config.save_path;
    %it should not happen
    if isempty(save_path)
        save_path = pwd;
    end
end

%store config name and save_path
setappdata(h.fig, 'Config', config_name);
setappdata(h.fig, 'Save_Path', save_path);

%%%%%%     GUI SetUp    %%%%%

%block parameters
block_pos = [0, 2, 3, 4, 5, 6] / 8;
block_size = [2, 1, 1, 1, 1, 2] / 8;
block_title_pos = [.95 .05];
block_title = {...
    'Data Directory' ...
    'Patient ID' ...
    'Scan' ...
    'Session' ...
    'Run' ...
    'PDF' ...
    };
block_filter = {...
    '.*' ...%data dir
    '*' ...%patient
    '*' ...%scan
    '*' ...%session
    '*' ...%run
    '*' ...%pdf
    };
block_filter_pos = [.9 .05];
block_select_all_pos = [.85 .05];
block_list_pos = [.1 .75];
block_select_none_pos = [.05 .05];

%set up all blocks
for block_ind = 1:6
    setup_block
end

    %nested function
    function setup_block
        uicontrol( ...
            'Style', 'text', ...
            'FontSize', 10, ...
            'FontWeight', 'bold', ...
            'Units', 'normalized', ...
            'Position', [block_pos(block_ind)  ...
                         block_title_pos(1)    ...
                         block_size(block_ind) ...
                         block_title_pos(2)],  ...
            'String', block_title{block_ind})
        h.block(block_ind).filter = uicontrol( ...
            'Parent', h.fig, ...
            'Style', 'edit', ...
            'BackgroundColor', [1 1 1], ...
            'Tag', 'filter', ...
            'CallBack', @dsel_callback,  ...
            'Units', 'normalized', ...
            'Position', [block_pos(block_ind) ...
                         block_filter_pos(1) ...
                         block_size(block_ind) ...
                         block_filter_pos(2)], ...
            'String', block_filter{block_ind});
        setappdata(h.block(block_ind).filter, 'Level', block_ind);
        h.block(block_ind).select_all = uicontrol( ...
            'Tag', 'select_all', ...
            'CallBack', @dsel_callback, ...
            'Units', 'normalized', ...
            'Position', [block_pos(block_ind) ...
                         block_select_all_pos(1) ...
                         block_size(block_ind) ...
                         block_select_all_pos(2)], ...
            'String', 'Select All');
        setappdata(h.block(block_ind).select_all, 'Level', block_ind);
        h.block(block_ind).block_list = uicontrol( ...
            'Tag', 'block_list', ...
            'CallBack', @dsel_callback,  ...
            'Units', 'normalized', ...
            'Position', [block_pos(block_ind) ...
                         block_list_pos(1) ...
                         block_size(block_ind) ...
                         block_list_pos(2)], ...
            'Style', 'listbox');
        setappdata(h.block(block_ind).block_list, 'Path', {});
        setappdata(h.block(block_ind).block_list, 'List', {});
        setappdata(h.block(block_ind).block_list, 'Select', logical([]));
        setappdata(h.block(block_ind).block_list, 'Level', block_ind);
        h.block(block_ind).select_none = uicontrol( ...
            'Tag', 'select_none', ...
            'CallBack', @dsel_callback, ...
            'Units', 'normalized', ...
            'Position', [block_pos(block_ind) ...
                         block_select_none_pos(1) ...
                         block_size(block_ind) ...
                         block_select_none_pos(2)], ...
            'String', 'Select None');
        setappdata(h.block(block_ind).select_none, 'Level', block_ind);
    end

%set up uicontrols (buttons and popupmenu)
button_size = [1/8 .05];
control_pos = [0 1 2 4 5 6 7] * button_size(1);
h.add_data = uicontrol( ...
    'Tag', 'add_path', ...
    'CallBack', @dsel_callback, ...
    'Units', 'normalized', ...
    'Position', [control_pos(1) 0 button_size], ...
    'String', 'Add Path');
h.remove_data = uicontrol( ...
    'Tag', 'remove_path', ...
    'CallBack', @dsel_callback, ...
    'Units', 'normalized', ...
    'Position', [control_pos(2) 0 button_size], ...
    'String', 'Remove Path');
h.tool_list = uicontrol( ...
    'Style', 'popupmenu', ...
    'Tag', 'tool_list', ...
    'CallBack', @dsel_callback, ...
    'Units', 'normalized', ...
    'Position', [control_pos(3) 0 2*button_size(1) button_size(2)], ...
    'String', tool_list);
h.add_tool = uicontrol( ...
    'Tag', 'add_tool', ...
    'CallBack', @dsel_callback, ...
    'Units', 'normalized', ...
    'Position', [control_pos(4) 0 button_size], ...
    'String', 'Add Tool');
h.remove_tool = uicontrol( ...
    'Tag', 'remove_tool', ...
    'CallBack', @dsel_callback, ...
    'Enable', 'off', ...
    'Units', 'normalized', ...
    'Position', [control_pos(5) 0 button_size], ...
    'String', 'Remove Tool');
h.apply = uicontrol( ...
    'Tag', 'apply', ...
    'CallBack', @dsel_callback, ...
    'Units', 'normalized', ...
    'Position', [control_pos(6) 0 button_size], ...
    'String', 'Save List');
h.exit = uicontrol( ...
    'Tag', 'exit', ...
    'CallBack', @dsel_callback, ...
    'Units', 'normalized', ...
    'Position', [control_pos(7) 0 button_size], ...
    'String', 'Exit');

%store handle structure
guidata(h.fig, h);

%set up default path
if ~isempty(config.data_path)
    for ii = 1:numel(config.data_path)
        data_path{ii} = ['+' config.data_path{ii}];
    end
    set(h.block(1).block_list, 'String', data_path);
    setappdata(h.block(1).block_list, 'Path', config.data_path);
    setappdata(h.block(1).block_list, 'List', config.data_path);
    setappdata(h.block(1).block_list, 'Select', true(1, numel(data_path)));
end

%to init lists 2 to 6
dsel_callback(h.fig, []);

%change figure tag, we might use it sometime
set(h.fig, 'Tag', 'figure');

end