function test = isconfig(filename)

if nargin < 1
    error('Too few input argumets');
end

if ~exist(filename, 'file')
    test = false;
    return
end

fid = fopen(filename, 'r', 'b');

if fid == -1
    error('Cannot open file %s', filename);
end

config = read_config_data(fid);

fclose(fid);

if isempty(config.version) || ...
   isempty(config.site_name) || ...
   isempty(config.dap_hostname) || ...
   isempty(config.sys_type) || ...
   isempty(config.sys_options) || ...
   isempty(config.supply_freq) || ...
   isempty(config.total_chans) || ...
   isempty(config.system_fixed_gain) || ...
   isempty(config.volts_per_bit) || ...
   isempty(config.total_sensors) || ...
   isempty(config.total_user_blocks) || ...
   isempty(config.next_derived_channel_number) || ...
   isempty(config.checksum) || ...
   isempty(config.reserved)

    test = false;
    return
end

test = true;